export const userSummary = {
    id: "user-1",
    name: "Aarav",
    city: "Bengaluru",
    gbitsTotal: 1240,
    gbitsThisWeek: 180,
    treesPlanted: 24,
    smartBinDrops: 12,
    waterSaves: 18,
    level: 7,
    nextLevelAt: 1500,
    streakDays: 26,
};

export const recentActions = [
    {
        id: "action-1",
        type: "Recycling",
        description: "Sorted mixed recyclables into the correct collection point",
        location: "Indiranagar Community Drop-off #04",
        date: new Date().toISOString(),
        gbits: 18,
        verification: "Community Event",
    },
    {
        id: "action-2",
        type: "Tree Planting",
        description: "Logged planting a neem sapling during a drive",
        location: "Community Park Plantation Drive",
        date: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
        gbits: 45,
        verification: "App Log",
    },
    {
        id: "action-3",
        type: "Water Saving",
        description: "Recorded a low-flow shower as part of a daily challenge",
        location: "Home",
        date: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
        gbits: 22,
        verification: "Survey",
    },
    {
        id: "action-4",
        type: "Transport",
        description: "Commuted 8km by cycle instead of car",
        location: "Office commute route",
        date: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
        gbits: 35,
        verification: "Manual",
    },
];

export const leaderboard = [
    {
        id: "leader-1",
        name: "Aarav",
        avatarColor: "bg-emerald-500",
        city: "Bengaluru",
        gbits: 1240,
        streakDays: 26,
    },
    {
        id: "leader-2",
        name: "Maya",
        avatarColor: "bg-lime-400",
        city: "Pune",
        gbits: 1180,
        streakDays: 19,
    },
    {
        id: "leader-3",
        name: "Kabir",
        avatarColor: "bg-teal-400",
        city: "Delhi",
        gbits: 1040,
        streakDays: 17,
    },
    {
        id: "leader-4",
        name: "Leela",
        avatarColor: "bg-emerald-300",
        city: "Chennai",
        gbits: 980,
        streakDays: 14,
    },
    {
        id: "leader-5",
        name: "Zara",
        avatarColor: "bg-green-300",
        city: "Mumbai",
        gbits: 930,
        streakDays: 12,
    },
];
